export default [
  {
    id: "100",
    title: "Pilsen x 12 Und",
    price: 58.00,
    offerPrice: null,
    stock: 12,
    img: "pilsenx12.jpg",
    category: "licores",
  },
  {
    id: "101",
    title: "Cristal x 12 Und",
    price: 53.00,
    offerPrice: null,
    stock: 12,
    img: "cristalx12.jpg",
    category: "licores",
  },
  {
    id: "102",
    title: "Cusqueña Trigo x 12 Und",
    price: 63.00,
    offerPrice: null,
    stock: 12,
    img: "cusqueñax12.jpg",
    category: "licores",
  },
  {
    id: "103",
    title: "Queirolo Acholado 750ml + Evervess 1.5Lt + Hielo",
    price: 40.00,
    offerPrice: null,
    stock: 12,
    img: "promo-acholado-queirolo.jpg",
    category: "licores",
  },
  {
    id: "104",
    title: "Ron Bacardi Carta de Oro 750ml + Pepsi 2Lt + Hielo",
    price: 30.00,
    offerPrice: 28.00,
    stock: 12,
    img: "promo-bacardi-750.jpg",
    category: "pack",
  },
  {
    id: "105",
    title: "Whisky JW Black Label 750ml + Guarana 3Lt + Hielo",
    price: 90.00,
    offerPrice: 88.00,
    stock: 12,
    img: "promo-black-label.jpg",
    category: "pack",
  },
  {
    id: "106",
    title: "Ron Carúpano 750ml + Pepsi 2Lt + Hielo",
    price: 19.00,
    offerPrice: 15.00,
    stock: 12,
    img: "promo-carupano.jpg",
    category: "pack",
  },
  {
    id: "107",
    title: "Whisky Chivas Regals 12 Años 750ml + Guarana 3Lt + Hielo",
    price: 90.00,
    offerPrice: 88.00,
    stock: 12,
    img: "promo-chivas.jpg",
    category: "pack",
  },
  {
    id: "108",
    title: "Pisco Porton Acholado + Evervess 1.5Lt + Hielo",
    price: 90.00,
    offerPrice: 85.00,
    stock: 12,
    img: "promo-porton.jpg",
    category: "pack",
  },
  {
    id: "109",
    title: "Whisky Something 750ml + Guarana 3Lt + Hielo",
    price: 47.00,
    offerPrice: 45.00,
    stock: 12,
    img: "promo-something.jpg",
    category: "pack",
  },
  {
    id: "110",
    title: "Cartavio Superior 750ml + Pepsi 2Lt + Hielo",
    price: 30.00,
    offerPrice: 24.00,
    stock: 12,
    img: "promo-superior-750.jpg",
    category: "pack",
  },
  {
    id: "111",
    title: "Vino Rosé Santiago Queirolo",
    price: 15.00,
    offerPrice: null,
    stock: 12,
    img: "rose.jpg",
    category: "licores",
  },
  {
    id: "112",
    title: "Vino Magdalena Santiago Queirolo",
    price: 15.00,
    offerPrice: null,
    stock: 12,
    img: "queirolo-rose.jpg",
    category: "licores",
  },
  {
    id: "113",
    title: "Vino Borgoña Tabernero",
    price: 15.00,
    offerPrice: 13.00,
    stock: 12,
    img: "tabernero-borgoña.jpg",
    category: "licores",
  },
  {
    id: "114",
    title: "Ceviche Mixto",
    price: 8.50,
    offerPrice: null,
    stock: 12,
    img: "ceviche.jpg",
    category: "comidas",
  },
  {
    id: "115",
    title: "Sudado Mixto",
    price: 14.88,
    offerPrice: 12.5,
    stock: 12,
    img: "chupe.jpg",
    category: "comidas",
  },
  {
    id: "116",
    title: "Sudado de Pescado",
    price: 20,
    offerPrice: null,
    stock: 12,
    img: "sudado.jpg",
    category: "comidas",
  },
  {
    id: "117",
    title: "Trio Marino",
    price: 15.00,
    offerPrice: null,
    stock: 12,
    img: "trio.jpg",
    category: "comidas",
  },
  {
    id: "118",
    title: "Trio Marino para 2 Personas",
    price: 25.00,
    offerPrice: 20.00,
    stock: 12,
    img: "trio2.jpg",
    category: "comidas",
  },
  {
    id: "119",
    title: "Ceviche de Pato",
    price: 14.99,
    offerPrice: 3.25,
    stock: 12,
    img: "cevichepato.jpg",
    category: "comidas",
  },
  {
    id: "200",
    title: "Bolsa de Papel con Lazo",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "bolsa.jpg",
    category: "manualidades",
  },
  {
    id: "201",
    title: "Bolsa Renos",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "bolsa2.jpg",
    category: "manualidades",
  },
  {
    id: "202",
    title: "Bolsas Estampadas",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "bolsa3.jpg",
    category: "manualidades",
  },
  {
    id: "203",
    title: "Amigumi Pack 4 Und",
    price: 5.00,
    offerPrice: null,
    stock: 12,
    img: "llavero1.jpg",
    category: "manualidades",
  },
  {
    id: "204",
    title: "Amigumi Azul",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "llavero-azul.jpg",
    category: "manualidades",
  },
  {
    id: "205",
    title: "Amigumi Turqueza",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "llavero-verde.jpg",
    category: "manualidades",
  },
  {
    id: "206",
    title: "Amigumi Colgador",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "llavero.jpg",
    category: "manualidades",
  },
  {
    id: "207",
    title: "Mantel a Crochet 20 x 20 cms",
    price: 5.88,
    offerPrice: null,
    stock: 12,
    img: "mantel.jpg",
    category: "manualidades",
  },
  {
    id: "208",
    title: "Titeres de Medio Cuerpo María y José",
    price: 20.88,
    offerPrice: null,
    stock: 12,
    img: "muñeco3.jpg",
    category: "manualidades",
  },
  {
    id: "209",
    title: "Títeres de Medio Cuerpo Jesús y sus discipulos",
    price: 14.88,
    offerPrice: null,
    stock: 12,
    img: "muñeco4.jpg",
    category: "manualidades",
  },
  {
    id: "210",
    title: "Titeres de Medio Cuerpo Amigos",
    price: 14.88,
    offerPrice: 10,
    stock: 12,
    img: "muñeco1.jpg",
    category: "manualidades",
  },
  {
    id: "211",
    title: "Muñeco Robot Corazón",
    price: 4.88,
    offerPrice: 4.0,
    stock: 12,
    img: "muñeco2.jpg",
    category: "manualidades",
  },
  {
    id: "212",
    title: "Titeres de Medio Cuerpo Enfermera Paciente",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "muñeco5.jpg",
    category: "manualidades",
  },
  {
    id: "300",
    title: "Transtornos de la Personalidad",
    price: 15.50,
    offerPrice: null,
    stock: 12,
    img: "transtornos-personalidad.jpg",
    category: "libros",
  },
  {
    id: "301",
    title: "Transtornos Neuroticos",
    price: 15.00,
    offerPrice: 10,
    stock: 12,
    img: "transtornos-neuroticos.jpg",
    category: "libros",
  },
  {
    id: "302",
    title: "Tortas Infantiles",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "tortas-infantiles.jpg",
    category: "libros",
  },
  {
    id: "303",
    title: "Diccionario Lexus Sinónimos y Antónimos",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "diccionario-sinonimos.jpg",
    category: "libros",
  },
  {
    id: "304",
    title: "Estructuras Metálicas Vol 1",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "estructuras-metalicas.jpg",
    category: "libros",
  },
  {
    id: "305",
    title: "Estructuras Metálicas Vol 2",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "proyectista.jpg",
    category: "libros",
  },
  {
    id: "306",
    title: "Titeres Hecho en Casa",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "titeres.jpg",
    category: "libros",
  },
  {
    id: "400",
    title: "Conjunto Niños Pack x 2 Und - Talla 12",
    price: 14.88,
    offerPrice: null,
    stock: 12,
    img: "conjunto-niño.jpg",
    category: "bazar",
  },
  {
    id: "401",
    title: "Vestido Niñas Talla 10 Pack x 3 Und",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "vestidos-niña.jpg",
    category: "bazar",
  },
  {
    id: "402",
    title: "Vestidos con Accesorios Talla 8 Pack x 3 Und",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "vestido-accesorios.jpg",
    category: "bazar",
  },
  {
    id: "403",
    title: "Buzos para Damas Talla M - Color Rosado",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "buzo-rosado.jpg",
    category: "bazar",
  },
  {
    id: "404",
    title: "Buzos para Caballeros Talla L  - Color Rojo",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "buzo-rojo.jpg",
    category: "bazar",
  },
  {
    id: "405",
    title: "Marcador Faber Castell Amarillo Fosforescente",
    price: 4.88,
    offerPrice: 3.99,
    stock: 12,
    img: "marcador.jpg",
    category: "bazar",
  },
  {
    id: "406",
    title: "Organizador para Papel A4",
    price: 8.88,
    offerPrice: 5,
    stock: 12,
    img: "organizador-papel.jpg",
    category: "bazar",
  },
  {
    id: "307",
    title: "Pack ütiles de Oficina",
    price: 24.88,
    offerPrice: 23.99,
    stock: 12,
    img: "utilies-oficina.jpg",
    category: "libros",
  },
  {
    id: "bread1",
    title: "Sprouts Classic Seedsational Bread 14 oz",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread.jpg",
    category: "postres",
  },
  {
    id: "bread2",
    title: "Traditional Corn Special Bread",
    price: 1.75,
    offerPrice: null,
    stock: 12,
    img: "bread2.jpg",
    category: "postres",
  },
  {
    id: "bread3",
    title: "Sprouts Classic Seedsational Bread",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread3.jpg",
    category: "postres",
  },
  {
    id: "toast",
    title: "Oven Baked Garlic & Cheese Toast",
    price: 1.7,
    offerPrice: null,
    stock: 12,
    img: "toast.jpg",
    category: "postres",
  },
  {
    id: "toast2",
    title: "Oven Baked Italian Herb with Olive Oil Toast",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "toast2.jpg",
    category: "postres",
  },
  {
    id: "cookies",
    title: "Raspberry Crumble Cookies",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "cookies.jpg",
    category: "postres",
  },
  {
    id: "cookies2",
    title: "Chocolate Chip Cookies",
    price: 3.0,
    offerPrice: null,
    stock: 12,
    img: "cookies2.jpg",
    category: "postres",
  },
  {
    id: "cookies3",
    title: "Freshly Baked Chocolate Chip Cookie",
    price: 2.5,
    offerPrice: null,
    stock: 12,
    img: "cookies3.jpg",
    category: "postres",
  },
  {
    id: "muffin",
    title: "Thomas Cinnamon Raisin English Muffins",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin.jpg",
    category: "postres",
  },

  {
    id: "muffin2",
    title: "Mini Zucchini & Carrot Muffin",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin2.jpg",
    category: "postres",
  },

  {
    id: "muffin3",
    title: "Double Chocolate Oat Muffin ",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin3.jpg",
    category: "postres",
  },

  {
    id: "Gaseosa Helada/ sin Helar",
    title: "Coca Cola 1Lt",
    price: 9.00,
    offerPrice: null,
    stock: 12,
    img: "cocacola1lt.jpg",
    category: "otros",
  },

  {
    id: "Gaseosa Helada / Sin Helar",
    title: "Inca Kola 1 Lt",
    price: 8.50,
    offerPrice: null,
    stock: 12,
    img: "incakola1lt.jpg",
    category: "otros",
  },

  {
    id: "coffe2",
    title: "Caffee Nero Mocha Late",
    price: 1.8,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    category: "otros",
  },

  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    price: 2.2,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    category: "otros",
  },

  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    category: "otros",
  },
];
