export default [
  {
    id: "1",
    title: "Pilsen x 12 Und",
    price: 61.00,
    offerPrice: 58.00,
    stock: 12,
    img: "pilsenx12.jpg",
    category: "licores",
  },
  {
    id: "2",
    title: "Cristal x 12 Und",
    price: 60.00,
    offerPrice: 53.00,
    stock: 12,
    img: "cristalx12.jpg",
    category: "licores",
  },
  {
    id: "3",
    title: "Cusqueña Trigo x 12 Und",
    price: 65.00,
    offerPrice: 63.00,
    stock: 12,
    img: "cusqueñax12.jpg",
    category: "licores",
  },
  {
    id: "4",
    title: "Queirolo Acholado 750ml + Evervess 1.5Lt + Hielo",
    price: 42.00,
    offerPrice: 40.00,
    stock: 12,
    img: "promo-acholado-queirolo.jpg",
    category: "licores",
  },
  {
    id: "5",
    title: "Ron Bacardi Carta de Oro 750ml + Pepsi 2Lt + Hielo",
    price: 35.00,
    offerPrice: 30.00,
    stock: 12,
    img: "promo-bacardi-750.jpg",
    category: "pack",
  },
  {
    id: "6",
    title: "Whisky JW Black Label 750ml + Guarana 3Lt + Hielo",
    price: 95.00,
    offerPrice: 90.00,
    stock: 12,
    img: "promo-black-label.jpg",
    category: "pack",
  },
  {
    id: "7",
    title: "Ron Carúpano 750ml + Pepsi 2Lt + Hielo",
    price: 25.00,
    offerPrice: 19.00,
    stock: 12,
    img: "promo-carupano.jpg",
    category: "pack",
  },
  {
    id: "8",
    title: "Whisky Chivas Regals 12 Años 750ml + Guarana 3Lt + Hielo",
    price: 90.00,
    offerPrice: 88.00,
    stock: 12,
    img: "promo-chivas.jpg",
    category: "pack",
  },
  {
    id: "9",
    title: "Pisco Porton Acholado + Evervess 1.5Lt + Hielo",
    price: 90.00,
    offerPrice: 85.00,
    stock: 12,
    img: "promo-porton.jpg",
    category: "pack",
  },
  {
    id: "11",
    title: "Whisky Something 750ml + Guarana 3Lt + Hielo",
    price: 47.00,
    offerPrice: 45.00,
    stock: 12,
    img: "promo-something.jpg",
    category: "pack",
  },
  {
    id: "22",
    title: "Cartavio Superior 750ml + Pepsi 2Lt + Hielo",
    price: 30.00,
    offerPrice: 24.00,
    stock: 12,
    img: "promo-superior-750.jpg",
    category: "pack",
  },
  {
    id: "33",
    title: "Vino Rosé Santiago Queirolo",
    price: 15.00,
    offerPrice: 13.00,
    stock: 12,
    img: "rose.jpg",
    category: "licores",
  },
  {
    id: "44",
    title: "Vino Magdalena Santiago Queirolo",
    price: 15.00,
    offerPrice: 13.00,
    stock: 12,
    img: "queirolo-rose.jpg",
    category: "licores",
  },
  {
    id: "55",
    title: "Vino Borgoña Tabernero",
    price: 15.00,
    offerPrice: 13.00,
    stock: 12,
    img: "tabernero-borgoña.jpg",
    category: "licores",
  },
  {
    id: "66",
    title: "Ceviche Mixto",
    price: 8.00,
    offerPrice: null,
    stock: 12,
    img: "ceviche.jpg",
    category: "comida",
  },
  {
    id: "77",
    title: "Sudado Mixto",
    price: 14.88,
    offerPrice: 12.5,
    stock: 12,
    img: "chupe.jpg",
    category: "comida",
  },
  {
    id: "88",
    title: "Sudado de Pescado",
    price: 20,
    offerPrice: null,
    stock: 12,
    img: "sudado.jpg",
    category: "comida",
  },
  {
    id: "99",
    title: "Trio Marino",
    price: 15.00,
    offerPrice: null,
    stock: 12,
    img: "trio.jpg",
    category: "comida",
  },
  {
    id: "00",
    title: "Trio Marino para 2 Personas",
    price: 25.00,
    offerPrice: null,
    stock: 12,
    img: "trio2.jpg",
    category: "comida",
  },
  {
    id: "111",
    title: "Ceviche de Pato",
    price: 14.99,
    offerPrice: 3.25,
    stock: 12,
    img: "cevichepato.jpg",
    category: "comida",
  },
  {
    id: "222",
    title: "Limon de Olmos x 1Kg",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "lemon.jpg",
    category: "ceviche",
  },
  {
    id: "333",
    title: "Aliquam lime dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lime.jpg",
    category: "ceviche",
  },
  {
    id: "444",
    title: "Aliquam mango dui non",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mango.jpg",
    category: "ceviche",
  },
  {
    id: "555",
    title: "Aliquam meat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat.jpg",
    category: "criollo",
  },
  {
    id: "666",
    title: "meat feugiat dui non mollis",
    price: 4.88,
    offerPrice: 4.0,
    stock: 12,
    img: "meat2.jpg",
    category: "criollo",
  },
  {
    id: "777",
    title: "Aliquam feugiat dui non meat",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat3.jpg",
    category: "criollo",
  },
  {
    id: "888",
    title: "mix vegetables feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mix.jpg",
    category: "crocante",
  },
  {
    id: "999",
    title: "pears feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "pears.jpg",
    category: "ceviche",
  },
  {
    id: "000",
    title: "Aliquam pepper dui non mollis",
    price: 4.88,
    offerPrice: 3.99,
    stock: 12,
    img: "pepper.jpg",
    category: "crocante",
  },
  {
    id: "1111",
    title: "Aliquam salmon dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "salmon.jpg",
    category: "criollo",
  },

  {
    id: "bread1",
    title: "Sprouts Classic Seedsational Bread 14 oz",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread.jpg",
    category: "postre",
  },
  {
    id: "bread2",
    title: "Traditional Corn Special Bread",
    price: 1.75,
    offerPrice: null,
    stock: 12,
    img: "bread2.jpg",
    category: "postre",
  },
  {
    id: "bread3",
    title: "Sprouts Classic Seedsational Bread",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread3.jpg",
    category: "postre",
  },
  {
    id: "toast",
    title: "Oven Baked Garlic & Cheese Toast",
    price: 1.7,
    offerPrice: null,
    stock: 12,
    img: "toast.jpg",
    category: "postre",
  },
  {
    id: "toast2",
    title: "Oven Baked Italian Herb with Olive Oil Toast",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "toast2.jpg",
    category: "postre",
  },
  {
    id: "cookies",
    title: "Raspberry Crumble Cookies",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "cookies.jpg",
    category: "postre",
  },
  {
    id: "cookies2",
    title: "Chocolate Chip Cookies",
    price: 3.0,
    offerPrice: null,
    stock: 12,
    img: "cookies2.jpg",
    category: "postre",
  },
  {
    id: "cookies3",
    title: "Freshly Baked Chocolate Chip Cookie",
    price: 2.5,
    offerPrice: null,
    stock: 12,
    img: "cookies3.jpg",
    category: "postre",
  },
  {
    id: "muffin",
    title: "Thomas Cinnamon Raisin English Muffins",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin.jpg",
    category: "postre",
  },

  {
    id: "muffin2",
    title: "Mini Zucchini & Carrot Muffin",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin2.jpg",
    category: "postre",
  },

  {
    id: "muffin3",
    title: "Double Chocolate Oat Muffin ",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin3.jpg",
    category: "postre",
  },

  {
    id: "Gaseosa Helada/ sin Helar",
    title: "Coca Cola 1Lt",
    price: 9.00,
    offerPrice: null,
    stock: 12,
    img: "cocacola1lt.jpg",
    category: "bebida",
  },

  {
    id: "Gaseosa Helada / Sin Helar",
    title: "Inca Kola 1 Lt",
    price: 8.50,
    offerPrice: null,
    stock: 12,
    img: "incakola1lt.jpg",
    category: "bebida",
  },

  {
    id: "coffe2",
    title: "Caffee Nero Mocha Late",
    price: 1.8,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    category: "bebida",
  },

  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    price: 2.2,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    category: "bebida",
  },

  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    category: "bebida",
  },
];
